# Generated by Django 4.1.3 on 2022-11-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
